# NOTE: Auto-generated by Azure/azure-cli workflow. Do not edit manually.
cask "azure-cli-pkg" do
  arch arm: "arm64", intel: "x86_64"

  version "1.0.0"
  sha256 arm:   "d5ccab6b66581179689c0e601596b7632e01eee7e0b0fc0c3a4c586f064aa06e",
         intel: "ad8e41ec159ebb0130c26bf963a4d1df5a0a40bf71d9d08ccca1c318e2767725"

  url "https://github.com/Azure/azure-cli/releases/download/azure-cli-pkg-v#{version}/azure-cli-#{version}-macos-#{arch}.pkg"
  name "Azure CLI"
  desc "Microsoft Azure command-line interface"
  homepage "https://learn.microsoft.com/cli/azure/"

  livecheck do
    url :url
    regex(/^azure-cli-pkg-v?(\d+(?:\.\d+)+)$/i)
  end

  depends_on macos: ">= :catalina"

  # Conflict with Homebrew formula version
  conflicts_with formula: "azure-cli"

  pkg "azure-cli-#{version}-macos-#{arch}.pkg"

  uninstall pkgutil: "com.microsoft.azure-cli",
            delete:  [
              "/usr/local/bin/az",
              "/usr/local/microsoft/azure-cli",
            ]

  zap trash: [
    "~/.azure",
  ]

  caveats <<~EOS
    Azure CLI has been installed successfully!
    
    Installation Details:
      • Executable: /usr/local/bin/az
      • Runtime: /usr/local/microsoft/azure-cli/
    
    This is a PKG-based installation with all dependencies bundled.
    No additional Homebrew formula dependencies required!
    
    To verify installation:
      az --version
    
    To get started:
      az login
      az account list
    
    Documentation:
      https://learn.microsoft.com/cli/azure/
  EOS
end
