# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-pkg-pj2" do
  version "1.0.0"

  on_arm do
    sha256 "e68399a4ffde7ef24ec1c42f5458a238b4035bf89ab54bd3dbe29b5241e08d50"
    url "https://github.com/naga-nandyala/pj2/releases/download/v1.0.0/mycli-1.0.0-macos-arm64.pkg"
  end

  on_intel do
    sha256 "116ea1b3b282f15c4e9e313ce08ae2d9710daa0c9f0a66c348b60089624fe702"
    url "https://github.com/naga-nandyala/pj2/releases/download/v1.0.0/mycli-1.0.0-macos-x86_64.pkg"
  end

  name "MyCLI App (PKG Installer)"
  desc "Azure-inspired CLI with native macOS installer"
  homepage "https://github.com/naga-nandyala/pj2"

  depends_on macos: ">= :catalina"

  on_arm do
    pkg "mycli-1.0.0-macos-arm64.pkg"
  end

  on_intel do
    pkg "mycli-1.0.0-macos-x86_64.pkg"
  end

  uninstall pkgutil: "com.naga-nandyala.mycli"

  caveats <<~EOS
    MyCLI installs directly to system locations:
      • Executable: /usr/local/bin/mycli
      • Runtime: /usr/local/libexec/mycli-venv/

    No symlinks or complex path resolution required.

    Basic usage:
      mycli --version
      mycli login
      mycli status

    To uninstall manually:
      sudo rm -f /usr/local/bin/mycli
      sudo rm -rf /usr/local/libexec/mycli-venv

    For the venv bundle version instead:
      brew install --cask naga-nandyala/mycli-app/mycli-app-venv-pj2
  EOS
end
# Force updated: 2025-09-24T10:50:58Z
