# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-venv-pj2" do
  version "1.0.0"

  on_arm do
    sha256 "ac37502d88340700e5120187f2db0b3d9a7d6d3f863542cccfc99cac22ecfd7e"
    url "https://github.com/naga-nandyala/pj2/releases/download/v#{version}/mycli-1.0.0-macos-arm64.tar.gz"
    binary "bin/mycli", target: "mycli"
  end

  on_intel do
    sha256 "a60031b75a87bd8ed130f2c1046f9451b225573bcf55964159eb4f7c89a0e06d"
    url "https://github.com/naga-nandyala/pj2/releases/download/v#{version}/mycli-1.0.0-macos-x86_64.tar.gz"
    binary "bin/mycli", target: "mycli"
  end

  name "MyCLI App (venv bundle)"
  desc "Azure-inspired CLI packaged with an embedded Python runtime"
  homepage "https://github.com/naga-nandyala/pj2"

  depends_on macos: ">= :catalina"

  caveats <<~EOS
    Installs a portable Python virtual environment containing all dependencies.

    Basic usage:
      mycli --help
      mycli login
      mycli status

    To install the PyInstaller build instead:
      brew install naga-nandyala/mycli-app/mycli-app
  EOS
end
