# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-pkgnew-pj2" do
  arch arm: "arm64", intel: "x86_64"

  version "4.0.0"
  sha256 arm:   "e57712a5a3792d33e5cad883f5accd24c23843a921b8bae8cf8f1cfd30c8af4a",
         intel: "51218ed196b47a9ad60dfe10d77d41803c7f6335f7f3cd79e13c54aca0d14bce"

  url "https://github.com/naga-nandyala/pj2/releases/download/v#{version}/mycli-#{version}-macos-#{arch}.pkg"
  name "MyCLI App (PKG Installer)"
  desc "Azure-inspired CLI with native macOS installer"
  homepage "https://github.com/naga-nandyala/pj2"

  livecheck do
    url :url
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end

  depends_on macos: ">= :catalina"

  pkg "mycli-#{version}-macos-#{arch}.pkg"

  uninstall pkgutil: "com.naga-nandyala.mycli"

  zap trash: [
    "~/.mycli",
    "~/.config/mycli",
  ]

  caveats <<~EOS
    MyCLI installs directly to system locations:
      • Executable: /usr/local/bin/mycli
      • Runtime: /usr/local/microsoft/mycli/

    No symlinks or complex path resolution required.

    Basic usage:
      mycli --version
      mycli login
      mycli status

    To uninstall manually:
      sudo rm -f /usr/local/bin/mycli
      sudo rm -rf /usr/local/microsoft/mycli
  EOS
end
