# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-pkg-pj2" do
  arch arm: "arm64", intel: "x86_64"

  version "2.1.0"
  sha256 arm:   "f19dbc0b0c6c14be2d08e8bd5e71980ffbdb3613f8f84593f0d1545dbbc57c6a",
         intel: "dc4997e55b50f81232964f35b681d873e0bd80dfcb8b4eb8f8673c50e18994e0"

  url "https://github.com/naga-nandyala/pj2/releases/download/v#{version}/mycli-#{version}-macos-#{arch}.pkg"
  name "MyCLI App (PKG Installer)"
  desc "Azure-inspired CLI with native macOS installer"
  homepage "https://github.com/naga-nandyala/pj2"

  livecheck do
    url :url
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end

  depends_on macos: ">= :catalina"

  pkg "mycli-#{version}-macos-#{arch}.pkg"

  uninstall pkgutil: "com.naga-nandyala.mycli"

  zap trash: [
    "~/.mycli",
    "~/.config/mycli",
  ]

  caveats <<~EOS
    MyCLI installs directly to system locations:
      • Executable: /usr/local/bin/mycli
      • Runtime: /usr/local/microsoft/mycli/

    No symlinks or complex path resolution required.

    Basic usage:
      mycli --version
      mycli login
      mycli status

    To uninstall manually:
      sudo rm -f /usr/local/bin/mycli
      sudo rm -rf /usr/local/microsoft/mycli
  EOS
end
