# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-pkgnew-pj2" do
  version "3.0.0"

  on_arm do
    sha256 "d57066e24ef4cdb7c164e1123baa382768d4f4b9a6913e5cdeeabc18dc42c4d1"
    url "https://github.com/naga-nandyala/pj2/releases/download/v3.0.0/mycli-3.0.0-macos-arm64.pkg"
  end

  on_intel do
    sha256 "d1754fecb7bee830dce172b9d9fd0a6caafb8fc7d138949604e8d862c9ddb309"
    url "https://github.com/naga-nandyala/pj2/releases/download/v3.0.0/mycli-3.0.0-macos-x86_64.pkg"
  end

  name "MyCLI App (PKG Installer)"
  desc "Azure-inspired CLI with native macOS installer"
  homepage "https://github.com/naga-nandyala/pj2"

  depends_on macos: ">= :catalina"

  on_arm do
    pkg "mycli-3.0.0-macos-arm64.pkg"
  end

  on_intel do
    pkg "mycli-3.0.0-macos-x86_64.pkg"
  end

  uninstall pkgutil: "com.naga-nandyala.mycli"

  caveats <<~EOS
    MyCLI installs directly to system locations:
      • Executable: /usr/local/bin/mycli
      • Runtime: /usr/local/libexec/mycli-venv/

    No symlinks or complex path resolution required.

    Basic usage:
      mycli --version
      mycli login
      mycli status

    To uninstall manually:
      sudo rm -f /usr/local/bin/mycli
      sudo rm -rf /usr/local/libexec/mycli-venv

    For the venv bundle version instead:
      brew install --cask naga-nandyala/mycli-app/mycli-app-venv-pj2
  EOS
end
