# NOTE: Auto-generated by workflow in mycli-app repo. Do not edit manually.
cask "mycli-app-pkg" do
  version "1.0.1"

  on_arm do
    sha256 "fa0f1f7b8cc9cadb8d77c1ba647ede084d9a2892689ac9809b251ac2410ebc3f"
    url "https://github.com/naga-nandyala/mycli-app/releases/download/v#{version}/mycli-app-1.0.1-arm64.pkg"
  end

  on_intel do
    sha256 "3f9e20f397f15a5ff7723e002b0fb0776b722deaeba6d0b35d600c59435f03f0"
    url "https://github.com/naga-nandyala/mycli-app/releases/download/v#{version}/mycli-app-1.0.1-x86_64.pkg"
  end

  name "MyCLI App (PKG Installer)"
  desc "Azure CLI-style tool for cloud operations with native macOS installer"
  homepage "https://github.com/naga-nandyala/mycli-app"

  # PKG installer approach
  pkg "mycli-app-#{version}-#{Hardware::CPU.arch}.pkg"

  # Binary will be installed to /usr/local/bin/mycli by the pkg installer
  binary "/usr/local/bin/mycli"

  # Uninstall options
  uninstall script: {
    executable: "/usr/local/bin/mycli-uninstall.sh",
    sudo:       true
  }

  # Postflight verification
  postflight do
    system_command "/usr/local/bin/mycli", args: ["--version"]
  end

  # Additional info for users
  caveats <<~EOS
    MyCLI App has been installed system-wide to /usr/local/bin/mycli
    
    Usage:
      mycli --help      # Show help
      mycli --version   # Show version  
      mycli login       # Login to Azure
      mycli status      # Check status
    
    To uninstall:
      sudo mycli-uninstall.sh
    
    Note: This version uses a native macOS .pkg installer for better
    system integration and security compliance.
  EOS
end
