# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-venv-pj2" do
  version "1.0.0"

  on_arm do
    sha256 "4795bd35eff2712da24844121ec35ce88b492797356b0bc4a36f0033bbee13ba"
    url "https://github.com/naga-nandyala/pj2/releases/download/v#{version}/mycli-1.0.0-macos-arm64.tar.gz"
    binary "mycli-1.0.0-macos-arm64/bin/mycli", target: "mycli"
  end

  on_intel do
    sha256 "e94eb564ad93d7fb1470f62f58b26c2cd92236eaa5c1d66489b653def9f15299"
    url "https://github.com/naga-nandyala/pj2/releases/download/v#{version}/mycli-1.0.0-macos-x86_64.tar.gz"
    binary "mycli-1.0.0-macos-x86_64/bin/mycli", target: "mycli"
  end

  name "MyCLI App (venv bundle)"
  desc "Azure-inspired CLI packaged with an embedded Python runtime"
  homepage "https://github.com/naga-nandyala/pj2"

  depends_on macos: ">= :catalina"

  caveats <<~EOS
    Installs a portable Python virtual environment containing all dependencies.

    Basic usage:
      mycli --help
      mycli login
      mycli status

    To install the PyInstaller build instead:
      brew install naga-nandyala/mycli-app/mycli-app
  EOS
end
