# NOTE: Auto-generated by workflow in mycli-app repo. Do not edit manually.
cask "mycli-app-pkg" do
  version "1.0.3"

  on_arm do
    sha256 "2d7e726d1c4e83478daf68d7edf7d1b2ed45b174907e4947cc3c206a85410968"
    url "https://github.com/naga-nandyala/mycli-app/releases/download/v#{version}/mycli-app-1.0.3-arm64.pkg"
  end

  on_intel do
    sha256 "4c49fc44a598f2166592b84e13c9225ba8cf58e580bddcfbd88446f55a853e18"
    url "https://github.com/naga-nandyala/mycli-app/releases/download/v#{version}/mycli-app-1.0.3-x86_64.pkg"
  end

  name "MyCLI App (PKG Installer)"
  desc "Azure CLI-style tool for cloud operations with native macOS installer"
  homepage "https://github.com/naga-nandyala/mycli-app"

  # PKG installer approach
  pkg "mycli-app-#{version}-#{Hardware::CPU.arch}.pkg"

  # Binary will be installed to /usr/local/bin/mycli by the pkg installer
  binary "/usr/local/bin/mycli"

  # Uninstall options
  uninstall script: {
    executable: "/usr/local/bin/mycli-uninstall.sh",
    sudo:       true
  }

  # Postflight verification
  postflight do
    system_command "/usr/local/bin/mycli", args: ["--version"]
  end

  # Additional info for users
  caveats <<~EOS
    MyCLI App has been installed system-wide to /usr/local/bin/mycli
    
    Usage:
      mycli --help      # Show help
      mycli --version   # Show version  
      mycli login       # Login to Azure
      mycli status      # Check status
    
    To uninstall:
      sudo mycli-uninstall.sh
    
    Note: This version uses a native macOS .pkg installer for better
    system integration and security compliance.
  EOS
end
