# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-pkg-pj2" do
  version "1.0.0"

  on_arm do
    sha256 "dcb496e77f59c637101b7b09e7c227e976de7b6703408d7d538e40bee77427fc"
    url "https://github.com/naga-nandyala/pj2/releases/download/v1.0.0/mycli-1.0.0-macos-arm64.pkg"
  end

  on_intel do
    sha256 "62f264ef4fb906c21c3b499e9236e245bbaf1cf52bfff1c2cb66dd500b6dd2a7"
    url "https://github.com/naga-nandyala/pj2/releases/download/v1.0.0/mycli-1.0.0-macos-x86_64.pkg"
  end

  name "MyCLI App (PKG Installer)"
  desc "Azure-inspired CLI with native macOS installer"
  homepage "https://github.com/naga-nandyala/pj2"

  depends_on macos: ">= :catalina"

  pkg on_arm: "mycli-1.0.0-macos-arm64.pkg",
      on_intel: "mycli-1.0.0-macos-x86_64.pkg"

  uninstall pkgutil: "com.naga-nandyala.mycli"

  caveats <<~EOS
    MyCLI installs directly to system locations:
      • Executable: /usr/local/bin/mycli
      • Runtime: /usr/local/libexec/mycli-venv/

    No symlinks or complex path resolution required.

    Basic usage:
      mycli --version
      mycli login
      mycli status

    To uninstall manually:
      sudo rm -f /usr/local/bin/mycli
      sudo rm -rf /usr/local/libexec/mycli-venv

    For the venv bundle version instead:
      brew install --cask naga-nandyala/mycli-app/mycli-app-venv-pj2
  EOS
end
# Force updated: 2025-09-24T10:21:54Z
