# NOTE: Auto-generated by naga-nandyala/azure-cli-pkg-1 workflow. Do not edit manually.
cask "azure-cli-pkg" do
  arch arm: "arm64", intel: "x86_64"

  version "1.0.0"
  sha256 arm:   "b59bc28a6941311992139adb22f23352eef76ea5e9f9a092de247cc6bc0d481e",
         intel: "5e3f4bd0501042e277452cae7d42892243358b9969464eff68da33a4e9d31467"

  url "https://github.com/naga-nandyala/azure-cli-pkg-1/releases/download/azure-cli-pkg-v#{version}/azure-cli-#{version}-macos-#{arch}.pkg"
  name "Azure CLI PKG"
  desc "Microsoft Azure command-line interface (PKG installer)"
  homepage "https://github.com/naga-nandyala/azure-cli-pkg-1"

  livecheck do
    url :url
    regex(/^azure-cli-pkg-v?(\d+(?:\.\d+)+)$/i)
  end

  depends_on macos: ">= :catalina"

  # Conflict with Homebrew formula version
  # conflicts_with formula: "azure-cli"

  pkg "azure-cli-#{version}-macos-#{arch}.pkg"

  uninstall pkgutil: "com.microsoft.azure-cli",
            delete:  [
              "/usr/local/bin/az",
              "/usr/local/microsoft/azure-cli",
            ]

  zap trash: [
    "~/.azure",
  ]

  caveats <<~EOS
    Azure CLI has been installed successfully!
    
    Installation Details:
      • Executable: /usr/local/bin/az
      • Runtime: /usr/local/microsoft/azure-cli/
    
    This is a PKG-based installation with all dependencies bundled.
    No additional Homebrew formula dependencies required!
    
    To verify installation:
      az --version
    
    To get started:
      az login
      az account list
    
    Documentation:
      https://learn.microsoft.com/cli/azure/
  EOS
end
