# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-pkgsign-pj2" do
  arch arm: "arm64", intel: "x86_64"

  version "5.0.1"
  sha256 arm:   "b6c526736731b600e81f6c67b8f839e50429da9dcceb5b751100e29cbeb38f82",
         intel: "e9e54ee171d34868e957770c42eac25da1ccd6f415df99c4d6b6c1b6cb9857da"

  url "https://github.com/naga-nandyala/pj2/releases/download/v#{version}/mycli-#{version}-macos-#{arch}.pkg"
  name "MyCLI App (Signed PKG Installer)"
  desc "Azure-inspired CLI with signed native macOS installer"
  homepage "https://github.com/naga-nandyala/pj2"

  livecheck do
    url :url
    strategy :github_latest
  end

  pkg "mycli-#{version}-macos-#{arch}.pkg"

  uninstall pkgutil: "com.naga-nandyala.mycli",
            delete:  [
              "/usr/local/bin/mycli",
              "/usr/local/microsoft/mycli",
            ]

  zap trash: [
    "~/.mycli",
    "~/Library/Application Support/mycli",
    "~/Library/Caches/mycli",
    "~/Library/Preferences/com.naga-nandyala.mycli.plist",
  ]

  caveats <<~EOS
    MyCLI has been installed with a signed PKG installer.

    The executable is available at:
      /usr/local/bin/mycli

    Usage:
      mycli --version
      mycli --help
      mycli login

    For authentication with Azure broker:
      mycli login --force-broker

    To uninstall:
      brew uninstall --cask mycli-app-pkgsign-pj2
  EOS
end
