# NOTE: Auto-generated by naga-nandyala/pj2 workflow. Do not edit manually.
cask "mycli-app-pkgnew-pj2" do
  arch arm: "arm64", intel: "x86_64"

  version "4.0.0"
  sha256 arm:   "af729e30efbee3d8d76a920da8fe526ae5b9791a778a7933e79a10037df54938",
         intel: "80f588f79043d623ad297264ee81604bf5ef9885678cafff40a3936c398aecf4"

  url "https://github.com/naga-nandyala/pj2/releases/download/v#{version}/mycli-#{version}-macos-#{arch}.pkg"
  name "MyCLI App (PKG Installer)"
  desc "Azure-inspired CLI with native macOS installer"
  homepage "https://github.com/naga-nandyala/pj2"

  livecheck do
    url :url
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end

  depends_on macos: ">= :catalina"

  pkg "mycli-#{version}-macos-#{arch}.pkg"

  uninstall pkgutil: "com.naga-nandyala.mycli"

  zap trash: [
    "~/.mycli",
    "~/.config/mycli",
  ]

  caveats <<~EOS
    MyCLI installs directly to system locations:
      • Executable: /usr/local/bin/mycli
      • Runtime: /usr/local/microsoft/mycli/

    No symlinks or complex path resolution required.

    Basic usage:
      mycli --version
      mycli login
      mycli status

    To uninstall manually:
      sudo rm -f /usr/local/bin/mycli
      sudo rm -rf /usr/local/microsoft/mycli
  EOS
end
